package dumpBackground2.gui.components.globalpanel;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

import dumpBackground2.gui.components.detailspanel.AffiliationDetailPanel;
import dumpBackground2.model.base.entity.Affiliation;

public class AffiliationGlobalPanel extends GlobalPanel<Affiliation>  {

	  /** Creates new form AffiliationGlobalSlavePanel */
	  public AffiliationGlobalPanel() {
	    initComponents();
	  }

	  @Override
	  public void refresh(Affiliation item) {

	    setMasterItem(item);

	   // this.affiliationDetailPanel.refreshItem(item);
	  //  this.affiliationSlaveAuthorsPanel.setMasterItem(item);
	   // this.affiliationSlaveDocumentsPanel.setMasterItem(item);

	    if (item != null) {
	      
	     // this.updateAffiliationButton.setEnabled(true);

	    } else {
	      
	     // this.updateAffiliationButton.setEnabled(false);

	    }
	  }

	  /** This method is called from within the constructor to
	   * initialize the form.
	   * WARNING: Do NOT modify this code. The content of this method is
	   * always regenerated by the Form Editor.
	   */
	  @SuppressWarnings("unchecked")
	  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	  private void initComponents() {

	 //   hideAndShowAffiliationPanel = new scimat.gui.components.HideAndShowPanel();
	    affiliationInfoPanel = new JPanel();
	    affiliationDetailPanel = new AffiliationDetailPanel();
	 //   updateAffiliationButton = new JButton();
	  //  hideAndShowAuthorPanel = new scimat.gui.components.HideAndShowPanel();
	    authorInfoPanel = new JPanel();
	  //  affiliationSlaveAuthorsPanel = new scimat.gui.components.slavepanel.AffiliationSlaveAuthorsPanel();
	   // hideAndShowDocumentPanel = new scimat.gui.components.HideAndShowPanel();
	    documentInfoPanel = new JPanel();
	   // affiliationSlaveDocumentsPanel = new scimat.gui.components.slavepanel.AffiliationSlaveDocumentsPanel();

	 //   this.hideAndShowAffiliationPanel.setDescription("Affiliation info");
	 //   this.hideAndShowAffiliationPanel.setPanel(this.affiliationInfoPanel);

	  /*  updateAffiliationButton.setText("Update");
	    updateAffiliationButton.addActionListener(new java.awt.event.ActionListener() {
	      public void actionPerformed(java.awt.event.ActionEvent evt) {
	        updateAffiliationButtonActionPerformed(evt);
	      }
	    });
*/
	    GroupLayout affiliationInfoPanelLayout = new GroupLayout(affiliationInfoPanel);
	    affiliationInfoPanel.setLayout(affiliationInfoPanelLayout);
	    affiliationInfoPanelLayout.setHorizontalGroup(
	      affiliationInfoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	      .addComponent(affiliationDetailPanel, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	      .addGroup(GroupLayout.Alignment.TRAILING, affiliationInfoPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        )
	    );
	    affiliationInfoPanelLayout.setVerticalGroup(
	      affiliationInfoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	      .addGroup(affiliationInfoPanelLayout.createSequentialGroup()
	        .addContainerGap()
	        .addComponent(affiliationDetailPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	       )
	    );

	    //this.hideAndShowAuthorPanel.setDescription("Authors info");
	    //this.hideAndShowAuthorPanel.setPanel(this.authorInfoPanel);

	    GroupLayout authorInfoPanelLayout = new GroupLayout(authorInfoPanel);
	    authorInfoPanel.setLayout(authorInfoPanelLayout);
	    authorInfoPanelLayout.setHorizontalGroup(
	      authorInfoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	      //.addComponent(affiliationSlaveAuthorsPanel, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	    );
	    authorInfoPanelLayout.setVerticalGroup(
	      authorInfoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	     // .addComponent(affiliationSlaveAuthorsPanel, GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
	    );

	 //   this.hideAndShowDocumentPanel.setDescription("Documents info");
	 //   this.hideAndShowDocumentPanel.setPanel(this.documentInfoPanel);

	    GroupLayout documentInfoPanelLayout = new GroupLayout(documentInfoPanel);
	    documentInfoPanel.setLayout(documentInfoPanelLayout);
	    documentInfoPanelLayout.setHorizontalGroup(
	      documentInfoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	     // .addComponent(affiliationSlaveDocumentsPanel, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	    );
	    documentInfoPanelLayout.setVerticalGroup(
	      documentInfoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	     // .addComponent(affiliationSlaveDocumentsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    );

	    GroupLayout layout = new GroupLayout(this);
	    this.setLayout(layout);
	    layout.setHorizontalGroup(
	      layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	      .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	        .addContainerGap()
	        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
	          .addComponent(documentInfoPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	          .addComponent(authorInfoPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	          .addComponent(affiliationInfoPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	         // .addComponent(hideAndShowAffiliationPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	         // .addComponent(hideAndShowAuthorPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	         // .addComponent(hideAndShowDocumentPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
	          )
	        .addContainerGap())
	    );
	    layout.setVerticalGroup(
	      layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	      .addGroup(layout.createSequentialGroup()
	      //  .addComponent(hideAndShowAffiliationPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(affiliationInfoPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
	      //  .addComponent(hideAndShowAuthorPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(authorInfoPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
	       // .addComponent(hideAndShowDocumentPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
	        .addComponent(documentInfoPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        .addContainerGap())
	    );
	  }// </editor-fold>//GEN-END:initComponents

	  /**
	   * 
	   * @param evt
	   */
	  private void updateAffiliationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAffiliationButtonActionPerformed

	    /*PerformKnowledgeBaseEditTask task;

	    // If the name is empty
	    if (this.affiliationDetailPanel.getFullAffiliation().isEmpty()) {

	      JOptionPane.showMessageDialog(this, "You have to give a full affiliation.\nPlease, " +
	        "give a full affiliation.", "Invalid full affiliation", JOptionPane.ERROR_MESSAGE);

	    } else {

	      task = new PerformKnowledgeBaseEditTask(new UpdateAffiliationEdit(getMasterItem().getAffiliationID(),
	              this.affiliationDetailPanel.getFullAffiliation()), this);

	      task.execute();
	    }*/
	  }//GEN-LAST:event_updateAffiliationButtonActionPerformed

	  // Variables declaration - do not modify//GEN-BEGIN:variables
	  private AffiliationDetailPanel affiliationDetailPanel;
	  private JPanel affiliationInfoPanel;
	  //private scimat.gui.components.slavepanel.AffiliationSlaveAuthorsPanel affiliationSlaveAuthorsPanel;
	  //private scimat.gui.components.slavepanel.AffiliationSlaveDocumentsPanel affiliationSlaveDocumentsPanel;
	  private JPanel authorInfoPanel;
	  private JPanel documentInfoPanel;
	  //private scimat.gui.components.HideAndShowPanel hideAndShowAffiliationPanel;
	  //private scimat.gui.components.HideAndShowPanel hideAndShowAuthorPanel;
	  //private scimat.gui.components.HideAndShowPanel hideAndShowDocumentPanel;
	  //private JButton updateAffiliationButton;
	  // End of variables declaration//GEN-END:variables
	}