package dumpBackground2.gui.components.manager;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.LayoutStyle;

import dumpBackground2.gui.components.globalpanel.GlobalPanel;
import dumpBackground2.gui.components.itemslist.GenericItemsListPanel;
import dumpBackground2.gui.components.itemslist.SelectionObserver;

/**
 *
 * @author mjcobo
 * 
 * @param <E> The main item
 */
public abstract class GenericItemManagerPanel<E extends Comparable<E>> extends JPanel implements SelectionObserver {

	/** Creates new form GenericItemManagerPanel */
	public GenericItemManagerPanel(GenericItemsListPanel<E> genericItemsListPanel, GlobalPanel<E> globalPanel) {

		this.genericItemsListPanel = genericItemsListPanel;
		this.globalPanel = globalPanel;

		initComponents();

		this.itemsListPanel.add(this.genericItemsListPanel);
		this.slaveScrollPanel.setViewportView(this.globalPanel);
		this.genericItemsListPanel.addSelectionObserver(this);

	}

	/**
	 * 
	 * @param title
	 */
	public void setMasterPanelTitle(String title) {

		masterScrollPanel.setBorder(BorderFactory.createTitledBorder(title));
	}

	/**
	 * 
	 * @param title
	 */
	public void setSlavePanelTitle(String title) {

		slaveScrollPanel.setBorder(BorderFactory.createTitledBorder(title));
	}

	/**
	 * 
	 * @param selection
	 */
	public void selectionChangeHappened(int[] selection) {

		/*
		 * if (selection.length == 0) {
		 * 
		 * this.globalPanel.refresh(null);
		 * 
		 * } else if (selection.length == 1) {
		 * 
		 * this.globalPanel.refresh(this.genericItemsListPanel.getItem(selection[0]));
		 * 
		 * } else {
		 * 
		 * this.globalPanel.refresh(null); }
		 */
	}

	public abstract void addAction();
// public abstract void removeAction(ArrayList<E> items);
// public abstract void moveToAction(ArrayList<E> items);

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		mainSplitPanel = new JSplitPane();
		masterScrollPanel = new JScrollPane();
		masterPanel = new JPanel();
		itemsListPanel = new JPanel();
		separator = new JSeparator();
		addButton = new JButton();
		/*
		 * moveToButton = new SelectionObserverButton(2,-1);
		 * this.genericItemsListPanel.addSelectionObserver(moveToButton); deleteButton =
		 * new SelectionObserverButton(1,-1);
		 * this.genericItemsListPanel.addSelectionObserver(this.deleteButton);
		 */
		slaveScrollPanel = new JScrollPane();

		mainSplitPanel.setBorder(null);
		mainSplitPanel.setDividerLocation(400);

		masterScrollPanel.setBorder(BorderFactory.createTitledBorder(""));

		itemsListPanel.setLayout(new BoxLayout(itemsListPanel, BoxLayout.LINE_AXIS));

		addButton.setText("Add");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		/*
		 * moveToButton.setText("Move to"); moveToButton.setEnabled(false);
		 * moveToButton.addActionListener(new java.awt.event.ActionListener() { public
		 * void actionPerformed(java.awt.event.ActionEvent evt) {
		 * moveToButtonActionPerformed(evt); } });
		 */

		/*
		 * deleteButton.setText("Delete"); deleteButton.setEnabled(false);
		 * deleteButton.addActionListener(new java.awt.event.ActionListener() { public
		 * void actionPerformed(java.awt.event.ActionEvent evt) {
		 * deleteButtonActionPerformed(evt); } });
		 */

		GroupLayout masterPanelLayout = new GroupLayout(masterPanel);
		masterPanel.setLayout(masterPanelLayout);
		masterPanelLayout.setHorizontalGroup(masterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(GroupLayout.Alignment.TRAILING,
						masterPanelLayout.createSequentialGroup().addContainerGap()
								.addGroup(masterPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
										.addComponent(itemsListPanel, GroupLayout.Alignment.LEADING,
												GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
										.addGroup(masterPanelLayout.createSequentialGroup().addComponent(addButton)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
												// .addComponent(moveToButton, GroupLayout.PREFERRED_SIZE,
												// GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										//// .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE,
										//// GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										).addComponent(separator, GroupLayout.Alignment.LEADING,
												GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
								.addContainerGap()));
		masterPanelLayout
				.setVerticalGroup(masterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(GroupLayout.Alignment.TRAILING, masterPanelLayout.createSequentialGroup()
								.addComponent(itemsListPanel, GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(separator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(masterPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										// .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE,
										// GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										// .addComponent(moveToButton, GroupLayout.PREFERRED_SIZE,
										// GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(addButton))
								.addContainerGap()));

		masterScrollPanel.setViewportView(masterPanel);

		mainSplitPanel.setLeftComponent(masterScrollPanel);

		slaveScrollPanel.setBorder(BorderFactory.createTitledBorder(""));
		mainSplitPanel.setRightComponent(slaveScrollPanel);

		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(mainSplitPanel,
				GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(mainSplitPanel,
				GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	/**
	 *
	 * @param evt
	 */
	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
		addAction();
	}// GEN-LAST:event_addButtonActionPerformed

	/**
	 * 
	 * @param evt
	 */
	private void moveToButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_moveToButtonActionPerformed

		// moveToAction(this.genericItemsListPanel.getSelectedItems());
	}// GEN-LAST:event_moveToButtonActionPerformed

	/**
	 * 
	 * @param evt
	 */
	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButtonActionPerformed

		// removeAction(this.genericItemsListPanel.getSelectedItems());
	}// GEN-LAST:event_deleteButtonActionPerformed

	/**
	 * 
	 * @param evt
	 */
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton addButton;
// private scimat.gui.components.SelectionObserverButton deleteButton;
	private JPanel itemsListPanel;
	private JSplitPane mainSplitPanel;
	private JPanel masterPanel;
	private JScrollPane masterScrollPanel;
	// private scimat.gui.components.SelectionObserverButton moveToButton;
	private JSeparator separator;
	private JScrollPane slaveScrollPanel;
	// End of variables declaration//GEN-END:variables
	 private GenericItemsListPanel<E> genericItemsListPanel;
	private GlobalPanel<E> globalPanel;

}