package dumpBackground2.gui.components.detailspanel;

import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

import dumpBackground2.model.base.entity.Affiliation;

/**
 *
 * @author Manuel Jesús Cobo Martin
 */
public class AffiliationDetailPanel extends GenericDetailPanel<Affiliation> {

  /** 
   * Creates new form WordDetailPanel
   */
  public AffiliationDetailPanel() {
    initComponents();

  //  CurrentProject.getInstance().getKbObserver().addAffiliationObserver(this);
  }

  /**
   *
   */
  public void reset() {

    idTextField.setText("");
    fullAffiliationTextField.setText("");

    setEnableTextField(false);
  }

  /**
   *
   */
  public void setEnableTextField(boolean enabled) {

    idTextField.setEnabled(enabled);
    fullAffiliationTextField.setEnabled(enabled);
  }

  /**
   * 
   * @param affiliation
   */
  public void refreshItem(Affiliation affiliation) {

    this.affiliation = affiliation;

    if (this.affiliation != null) {

      idTextField.setText(this.affiliation.getAffiliationID().toString());
      fullAffiliationTextField.setText(this.affiliation.getFullAffiliation());
      
      setEnableTextField(true);

    } else {

      reset();

    }
  }

  /**
   * 
   * @return
   */
  public String getFullAffiliation() {

    return fullAffiliationTextField.getText();
  }

  /**
   *
   * @param items
   * @throws KnowledgeBaseException
   */
  public void entityAdded(ArrayList<Affiliation> items)  {
    // Do Nothing
  }

  /**
   * 
   * @param items
   * @throws KnowledgeBaseException
   */
  public void entityRemoved(ArrayList<Affiliation> items)  {
    // Do Nothing
  }

  /**
   *
   * @param entity
   * @throws KnowledgeBaseException
   */
  public void entityRefresh()  {
    // Do Nothing
  }

  /**
   * 
   * @param items
   * @throws KnowledgeBaseException
   */
  public void entityUpdated(ArrayList<Affiliation> items)  {

    int position;

    position = items.indexOf(this.affiliation);

    if (position != -1) {

      refreshItem(items.get(position));

    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    idDescriptionLabel = new JLabel();
    idTextField = new JTextField();
    fullAffiliationDescriptionLabel = new JLabel();
    fullAffiliationTextField = new JTextField();

    idDescriptionLabel.setText("ID:");

    idTextField.setEnabled(false);

    fullAffiliationDescriptionLabel.setText("Full affiliation:");

    GroupLayout layout = new GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(idDescriptionLabel)
          .addComponent(fullAffiliationDescriptionLabel))
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(idTextField, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addComponent(fullAffiliationTextField, GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
          .addComponent(idDescriptionLabel)
          .addComponent(idTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
          .addComponent(fullAffiliationDescriptionLabel)
          .addComponent(fullAffiliationTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel fullAffiliationDescriptionLabel;
  private JTextField fullAffiliationTextField;
  private JLabel idDescriptionLabel;
  private JTextField idTextField;
  // End of variables declaration//GEN-END:variables
  private Affiliation affiliation = null;
}