package dumpBackground2.gui.components.detailspanel;

import javax.swing.GroupLayout;

import javax.swing.JPanel;

/**
 *
 * @author mjcobo
 */
public abstract class GenericDetailPanel<E extends Comparable<E>> extends JPanel {

  /** Creates new form GenericDetailPanel */
  public GenericDetailPanel() {
    initComponents();
  }
  
  public abstract void refreshItem(E item);

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    GroupLayout layout = new GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 139, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 105, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}